atomicchar:
  tsc --noImplicitAny --module commonjs atomic-wrapper.ts --out atomic-wrapper.js --outDir ../
  
atomicchar10:
  "C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\tsc" --noImplicitAny --module commonjs atomic-wrapper.ts --out atomic-wrapper.js --outDir ../
  
clean:
  rm ../atomic-wrapper.js
